# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Business-SLA
version:      0.01
version_from: lib/Business/SLA.pm
installdirs:  site
requires:
    Business::Hours:               0
    Test::Inline:                  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
