--- #YAML:1.0
name:                Business-SLA
version:             0.05
abstract:            
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    Business::Hours:               0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Linda Julien <leira@bestpractical.com>
